//
//  Product.m
//  MacysTest
//
//  Created by Paul Wong on 5/11/14.
//  Copyright (c) 2014 Paul Wong. All rights reserved.
//

#import "Product.h"

@interface Product()

/**
 If the photo name is known, for example, "MockProductPhoto1.png" (as given in the MockData.json file), then that is productPhotoName and productPhoto is exactly [UIImage imageNamed:self.productPhotoName]. Otherwise, productPhotoName is assumed to be nil and productPhoto is generated by [UIImage imageWithContentsOfFile:[self photoPath]].
 */
@property (nonatomic) NSString *productPhotoName;

@end

@implementation Product

- (id)initWithId:(NSInteger)productId andName:(NSString *)productName andDescription:(NSString *)productDescription andRegularPrice:(CGFloat)productRegularPrice andSalePrice:(CGFloat)productSalePrice andPhotoName:(NSString *)productPhotoName andColors:(NSArray *)productColors andStores:(NSDictionary *)productStores {
    self = [super init];
    if (self) {
        self.productId = productId;
        self.productName = productName;
        self.productDescription = productDescription;
        self.productRegularPrice = productRegularPrice;
        self.productSalePrice = productSalePrice;

        self.productPhotoName = productPhotoName;
        self.productPhoto = [self photoImage];
        
        self.productColors = productColors;
        self.productStores = productStores;
    }
    return self;
}

#pragma mark - Utilities

- (NSString *)documentsDirectory {
    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
    NSString *documentsDirectory = [paths objectAtIndex:0];
    return documentsDirectory;
}

#pragma mark - Public Methods

- (NSString *)photoPath {
    NSString *filename = [NSString stringWithFormat:@"Photo%ld.png", (long)self.productId];
    return [[self documentsDirectory] stringByAppendingPathComponent:filename];
}

+ (NSInteger)nextId {
    NSUserDefaults *userDefaults = [NSUserDefaults standardUserDefaults];
    NSInteger nextProductId = [userDefaults integerForKey:@"NextId"];
    if (nextProductId == 0) {
        // Let product id start from 1, not 0, just to be consistent with SQLite convention.
        nextProductId = 1;
    }
    [userDefaults setInteger:nextProductId+1 forKey:@"NextId"];
    [userDefaults synchronize];
    return nextProductId;
}

#pragma mark - Private Methods

- (UIImage *)photoImage {
    if (self.productPhotoName) {
        return [UIImage imageNamed:self.productPhotoName];
    }
    else {
        return [UIImage imageWithContentsOfFile:[self photoPath]];
    }
}

@end
